### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by patrickhernon** [Budibase/svelte-ag-grid#10]
Could you please add a license to this code i.e. if its open source, to add the appropriate open source license

**Comment by mjashanks** [comment]
Done - licensed under MIT - thanks!

**Comment by patrickhernon** [comment]
Thanks. Would it be possible to release a new package version to npmjs now that the license has been added?

**Comment by mjashanks** [comment]
Yes - also done!

**Comment by patrickhernon** [comment]
Thanks!
