### ISSUE TITLE
Should `grid` be destroyed?

### ISSUE THREAD

**Issue by roydukkey** [Budibase/svelte-ag-grid#2]
> **destroy()**
> Will destroy the grid and release resources. If you are using Angular (version 1 or 2) you do not need to call this, as the grid links in with the AngularJS 1.x lifecycle. However if you are using Web Components or native Javascript, you do need to call this, to avoid a memory leak in your application.
>
> ref: https://www.ag-grid.com/javascript-grid-api/

The grid is created on mount, likewise then, shouldn't it be destroyed when the svelte component is destroyed?

```js
  onDestroy(() => {
    if (grid) {
      grid.destroy();
    }
  });
```

**Comment by shogunpurple** [comment]
Closed by https://github.com/Budibase/svelte-ag-grid/pull/5

**Comment by brunobely** [comment]
Should `api = null;` also be called? Otherwise the parent will keep the reference when using `bind:api={gridApi}`.

I keep getting errors like this when binding to `api`:

```
 Grid: Grid API function onFilterChanged() cannot be called as the grid has been destroyed.
                     Please don't call grid API functions on destroyed grids - as a matter of fact you shouldn't
                     be keeping the API reference, your application has a memory leak! Remove the API reference
                     when the grid is destroyed.
```
