### ISSUE TITLE
Theme style sheets are loaded multiple times.

### ISSUE THREAD

**Issue by roydukkey** [Budibase/svelte-ag-grid#6]
<img width="768" alt="Screen Shot 2020-12-11 at 19 06 15" src="https://user-images.githubusercontent.com/1509616/101965825-f93be880-3be3-11eb-96a2-7775f12c6fb3.png">

This can be avoided by using sourcing `document.styleSheets` to determine if the stylesheet has already been added. The feature is listed as experimental, but the [support is great](https://caniuse.com/mdn-api_documentorshadowroot_stylesheets) and the are no notes about existing issues.

**Comment by shogunpurple** [comment]
Closed with https://github.com/Budibase/svelte-ag-grid/pull/7
